### ISSUE TITLE
Forking todo list

### ISSUE THREAD

**Issue by gerrymanoim** [gerrymanoim/exchange_calendars#1]
# Organizational 

- [x] come up with a new name `exchange_calendars`
- [x] Rename all the relevant pieces
- [x] set up pypi
- [ ] set up conda-forge
- [x] Update on https://github.com/rsheftel/pandas_market_calendars/issues/120
- [x] Look into whether licensing needs to/can change
- [x] change links pointing everywhere 
- [x] remove zipline references

# Code 

These will all be breaking changes. 
 
- [x] drop py2
- [x] drop python < 3.7 (we follow https://numpy.org/neps/nep-0029-deprecation_policy.html / pandas now)
- [x] drop old pandas/numpy
- [x] drop one minute thing https://github.com/gerrymanoim/trading_calendars#why-are-open-times-one-minute-late
- [ ] what else can be deprecated?
   - [ ] https://github.com/gerrymanoim/trading_calendars/blob/master/trading_calendars/errors.py
   - [ ] use of nyse?

# Etc

- [ ] Publish docs
- [ ] Clarify user contributed nature of calendars in issue templates

**Comment by zfsamzfsam** [comment]
quantrocket-llc/trading-calendars
	https://github.com/quantrocket-llc/trading-calendars
	add country_code to all calendars

quantrocket-llc/quantrocket-trading-calendars
	https://github.com/quantrocket-llc/quantrocket-trading-calendars
	This package differs from the underlying quantopian/trading_calendars package in that 
		it provides additional support for Interactive Brokers exchange codes and other exchange codes used in QuantRocket.

**Comment by rsheftel** [comment]
@zfsamzfsam so the changes are that the aliases include the ones required for IB?
