### ISSUE TITLE
todo when min support moves to python 3.8

### ISSUE THREAD

**Issue by maread99** [gerrymanoim/exchange_calendars#68]
- [x] lose memoize.py \ `@lazyval` in favour of `@functools.cached_property`
- [x] on `Answers` and `ExchangeCalendar` classes consolidate properties returning functions decorated `@functools.lru_cache` with simple properties decorated with `@functools.cached_property`
- [x] use Literal to annotate selection of string values, to include at least:
  - [x] `direction` parameter of `ExchangeCalendar`, `minute_to_session_label` and `date_to_session_label` methods as Literal["next", "previous", "none"]
  - [x] `side` parameter of `ExchangeCalendar`, `test_exchange_calendar.py` and `calendar_helper.py` methods as Literal["left", "right", "both", "neither"]
  - [x] `column` parameter of `Answers._get_sessions_with_times_different_to_a_contiguous_session` as Literal["opens", "closes", "break_starts", "break_ends"]

**Comment by maread99** [comment]
Incorporated in #187 for v4.
