### ISSUE TITLE
Path to release 3.4

### ISSUE THREAD

**Issue by maread99** [gerrymanoim/exchange_calendars#86]
I'm taking the liberty to assume that the process started with PR #71 (to add a 'side' option and overhaul the test suite) will culminate in cutting 3.4. The process...

- [ ] Complete, review and merge #71.
- [ ] PR to replace ExchangeCalendarTestBase with ExchangeCalendarTestBaseProposal for the first five calendar test modules to which proposed base already incorporated by #71 (to include moving over calendar-specific tests).
- [ ] Move all calendar test modules over to new test base (over various PRs).
- [ ] PR new minute-related methods.
- [ ] Review whether to move *minute_nanos(side=None) methods , which can currently override default side, to properties that return for default side only (would require revising minute_index_to_session_labels).
- [ ] PR to rename ExchangeCalendar methods (only if implementing #85).
- [ ] Revise README to:
  - Clearly express concepts of 'session(s}' and 'minute(s)'.
  - Explain 'side' option.
  - Ensure not referring to any 'old method names' (only relevant if implementing #85).
- [ ] Cut 3.4.
