### ISSUE TITLE
todo when min support moves to python 3.9

### ISSUE THREAD

**Issue by maread99** [gerrymanoim/exchange_calendars#98]
- [x] ~`ExchangeCalendar` class methods `valid_sides` and `default_side` to be changed to class properties (like [this](https://stackoverflow.com/questions/128573/using-property-on-classmethods/64738850#64738850)).~ EDIT 06/06/22 - **NOTE:** seems that defining class properties in this way may not be an option from 3.11 (same [reference](https://stackoverflow.com/questions/128573/using-property-on-classmethods/64738850#64738850)). If it's not going to stable then leave as is.
- [x] Remove following `ExchangeCalendar` methods deprecated in 4.0 (will be about time to remove them).
  - `sessions_opens`
  - `sessions_closes`
- [x] Check if it's still necessary to have the 'near-empty' setup.py file to allow for editable installs when defining meta in pyproject.toml ([reference](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html)). Remove `setup.py` if it's no longer needed, otherwise roll this item forwards to review when bumping min support to 3.10.
- [x] **Drop `pytz` in favor of `zoneinfo`** standard library ~(either now or later). [Looks likely](https://github.com/pandas-dev/pandas/issues/44823) that pandas 2.0 will switch to `zoneinfo` as its default timezone package. If it looks like pandas 2.0 could be released any time soon we might want to address this now. If it looks still to be a way off then we could roll this item forwards (to dedicated issue), although in any event pandas already supports `zoneinfo` and we'd be better off depending on a stdlib library than a third-party one.~ See #322.

On bumping min version to 3.9, roll anything not addressed to a new issue 'TODO when min support moves to python 3.10'.
